services:
  - type: web
    name: think-studio
    env: python
    region: singapore
    plan: free
    buildCommand: ""
    startCommand: python server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
